### ISSUE TITLE
Frontend: issue with header and footer

### ISSUE THREAD

**Issue by AshenDulsanka** [AshenDulsanka/BookKing-Website-PUSL2021#88]
the header and footer is not functioning correctly

**Comment by AshenDulsanka** [comment]
header

![image](https://github.com/AshenDulsanka/BookKing-Website-PUSL2021/assets/104350487/c8c026d1-a726-44db-b4ba-ee4f5f71aa56)

**Comment by AshenDulsanka** [comment]
now the header is correct, but still the footer is not

![image](https://github.com/AshenDulsanka/BookKing-Website-PUSL2021/assets/104350487/7b6ea812-f895-40dc-b0ce-38916e4e3860)

**Comment by rasithsenanayake** [comment]
fixed header footer in sign up pages and login pages

**Comment by rasithsenanayake** [comment]
service provider login , signup and user login , sign up footer fixed
